[theme]
base                     = "light"        # change to "dark" to switch modes
primaryColor             = "#78d4e9ff"      # violet accent for widgets
backgroundColor          = "#f8f9fa"      # off-white page background
secondaryBackgroundColor = "#9ceaffff"      # light-violet panels / sidebar
textColor                = "#262730"      # near-black text
baseRadius               = "large"        # radius used as basis for the corners of most UI elements
font                     = "Roboto"      # Google-font string do, wont work!!

